// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KVList struct {
	_tab flatbuffers.Table
}

func GetRootAsKVList(buf []byte, offset flatbuffers.UOffsetT) *KVList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KVList{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *KVList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KVList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KVList) Kvs(obj *KV, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *KVList) KvsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func KVListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func KVListAddKvs(builder *flatbuffers.Builder, kvs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(kvs), 0)
}
func KVListStartKvsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func KVListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
